#!/bin/bash -e

# RANDOM NOTES, NOT PART OF THE PROJECT!!!!!!!!!!!!!!!!!


# git clone https://github.com/lhmouse/nano-win.git
# cd nano-win

# sed quick reference https://anaturb.net/sed.htm

# gcc options guide https://gcc.gnu.org/onlinedocs/gcc/Warning-Options.html#Warning-Options 

# PDCurses reference: https://pdcurses.org/docs/USERS.html
#       https://www.demo2s.com/c/c-doupdate-hdfm.html 

# Unicode Calculator https://www.branah.com/unicode-converter

# last commit name
git show -s --format=%s

# last commit message
git log -1 --pretty=%B

# last commit message with date
git log -1


# Date of last modification

git clone --depth=1 git://git.savannah.gnu.org/nano.git
cd nano

A=$( TZ=UTC git show --quiet --date='format-local:%Y-%m-%dT%H:%M:%SZ' --format="%cd" )


# Get date from latest release

B=$( wget -q https://api.github.com/repos/okibcn/myopenwrt/releases/latest -O - | awk -F \" -v RS="," '/published_at/ {print $(NF-1)}' )

# Dates comparison

if [[ $A<$B ]]; then echo "primero menor"; else echo "segundo menor"; fi


# Current UTC time:
TZ=UTC date +'%Y.%m.%dT%H:%M:%SZ'



git describe --tags 2>/dev/null` for Windows, build `git rev-list --count HEAD



# Compile ncurses
i686-w64-mingw32-gcc -DHAVE_CONFIG_H -I. -I../../../src -I..  -DLOCALEDIR=\"/home/user/nano/pkg_i686-w64-mingw32/share/locale\" -DSYSCONFDIR=\"C:\ProgramData\" -I../lib -I../../../lib -I"/home/user/nano/pkg_i686-w64-mingw32/include/ncursesw" -DNCURSES_STATIC -D__USE_MINGW_ANSI_STDIO -I"/home/user/nano/pkg_i686-w64-mingw32/include"  -O2 -g3 -flto -Wall -MT nano.o -MD -MP -MF .deps/nano.Tpo -c -o nano.o ../../../src/nano.c

#Link ncurses
i686-w64-mingw32-gcc  -O2 -g3 -flto -Wall  -L"/home/user/nano/pkg_i686-w64-mingw32/lib/" -static -flto -static-libgcc -o nano.exe browser.o chars.o color.o cut.o files.o global.o help.o history.o move.o nano.o prompt.o rcfile.o search.o text.o utils.o winio.o ../lib/libgnu.a  -pthread -lshlwapi -lncursesw



# Compile pdcurses vt
i686-w64-mingw32-gcc -Wall -Wextra -pedantic -Werror -O2 -fPIC -DPDC_FORCE_UTF8 -I.. -DHAVE_VSNPRINTF -DHAVE_VSSCANF -c ../vt/pdcutil.c
# Compile pdcurses wincon
i686-w64-mingw32-gcc -c -Wall -Wextra -pedantic -O3 -I.. -DPDC_FORCE_UTF8 ../vt/pdcutil.c
# link lib
i686-w64-mingw32-ar rv libpdcurses.a addch.o addchstr.o ...

# Single source vt
i686-w64-mingw32-gcc -Wall -Wextra -pedantic -Werror -O2 -fPIC -DPDC_FORCE_UTF8 -I..  -o testcurs.exe ../demos/testcurs.c libpdcurses.a
# Single source wincon
i686-w64-mingw32-gcc -Wall -Wextra -pedantic -O3 -I.. -DPDC_FORCE_UTF8 -otestcurs.exe ../demos/testcurs.c pdcurses.a -lwinmm
# Multi source vt
i686-w64-mingw32-gcc -Wall -Wextra -pedantic -Werror -O2 -fPIC -DPDC_FORCE_UTF8 -I.. -c  ../demos/tui.c
i686-w64-mingw32-gcc tui.o tuidemo.o -o tuidemo.exe libpdcurses.a
# Multi source wincon
i686-w64-mingw32-gcc -c -Wall -Wextra -pedantic -O3 -I.. -DPDC_FORCE_UTF8 -I../demos -otui.o ../demos/tui.c
i686-w64-mingw32-gcc  -otuidemo.exe tuidemo.o tui.o pdcurses.a -lwinmm



x86_64-w64-mingw32-gcc -I/home/user/nano/PDcursesMod -DPDC_FORCE_UTF8 -ombrot.exe mbrot.c /home/user/nano/PDcursesMod/wincon/pdcurses.a -lwinmm

x86_64-w64-mingw32-gcc -I/home/user/nano/PDcursesMod -DPDC_FORCE_UTF8 mbrot.c /home/user/nano/PDcursesMod/wincon/pdcurses.a -lwinmm  -ombrot.exe 


x86_64-w64-mingw32-gcc  -I/home/user/nano/PDcursesMod -DPDC_FORCE_UTF8 -D__USE_MINGW_ANSI_STDIO -Wall  -L/home/user/nano/PDcursesMod/wincon -static -static-libgcc -o nano.exe browser.o chars.o color.o cut.o files.o global.o help.o history.o move.o nano.o prompt.o rcfile.o search.o text.o utils.o winio.o ../lib/libgnu.a /home/user/nano/PDcursesMod/wincon/pdcurses.a -pthread -lwinmm -lshlwapi




nano main()
 rcfile do_rcfiles() Search the right nanorc
  rcfile parse_one_nanorc() Checks if file can be opened
   rcfile parse_rcfile() parse nanorc for all elements
    rcfile parse_interface_color() ctreates the trio fg,bg,attr
     rcfile parse_combination() ctreates the trio fg,bg,attr
      rcfile color_to_short() color to integer, including 
       rcfile closest_index_color() code color to the nearest possible
color set_interface_colorpairs() takes colorcombo trio to interface_color_pair[int].
 pdc color init_pair()  
  pdc color init_extended_pair()  Checks some errors
   pdc color _init_pair_core()  does the job

nanorc process_a_keystroke(void) wait for a key and...
 winio get_kbinput(WIN,showcursor) manages cursor visibility
  winio parse_kbinput(WIN) Most of key translation is done here <<<<<<<<
   winio int get_input(WIN) used in search too. asks to fill buffer from:
    winio void read_keys_from(WIN)   insert raw codes in buffer.
     pdc wgetch()
    winio int get_code_from_plantation()  returns the code from rcfile or seeds the actions

cut copy_text() copy to linestruct *cutbuffer
cut paste_text() paste 
cut do_delete() normal or tiny
 cut zap_text(void)

		fprintf(stderr, "tic..."); //o//
		fprintf(stderr, "tac\n"); //o//
fprintf(stderr, "\nParse_kbinput returns: %3x - %s\n", kbinput, keyname(kbinput)); //o//


alias pdmake='\
cd ~/nano/PDCursesMod/wingui;\
 make clean ;\
  make -j12 WIDE=Y UTF8=Y _w64=Y demos ;\
  cp -f *.exe ~/desktop/demos
      cp pdcurses.a libncursesw.a ; \
    cp pdcurses.a libpdcurses.a ; \
    cp pdcurses.a libncurses.a ; \
  cd ~/nano/build_x86_64-w64-mingw32/nano ; \
  make -j12 ; cp -f src/nano.exe ~/desktop'



if (!PDC_get_key_modifiers()) { //o//
    switch (keycode) { //o//
        case 0x08:      return KEY_BACKSPACE; //o//
        case '\n':      return KEY_ENTER; //o//
    } //o//
} //o//
 

